In [ ]:
import pandas as pd

Preparación de librería Spotipy

In [ ]:
!pip install spotipy --upgrade

In [ ]:
SPOTIPY_CLIENT_ID ='mycliendid'
SPOTIPY_CLIENT_SECRET ='myclientsecret'

In [ ]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

auth_manager = SpotifyClientCredentials(SPOTIPY_CLIENT_ID,SPOTIPY_CLIENT_SECRET)

sp = spotipy.Spotify(auth_manager=auth_manager)

Carga y preparación de datos

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/pdg/Datos/lyrics/EnEsSongsDataset.csv');

In [ ]:
df.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,name,id,artist,genre,popularity,hit,lyricsBillboard,lyric,language
0,0,0,0,Yellow,36Owb6DDJbBFXi86x3X61z,Pity Party (Girls Club),Pop,62,NaN,NaN,"Love is sick, but we could try\nI really like,...",en
1,1,1,1,Kryptonite,6ZOBP3NvffbU4SZcrnt1k6,3 Doors Down,Pop,79,1.0,NaN,"Well, I took a walk around the world to ease m...",en
2,2,2,2,Ms. Jackson,0I3q5fE6wg7LIfHGngUTnV,Outkast,Pop,81,1.0,NaN,Yeah this one right here goes out to all the b...,en
3,3,3,3,It Wasn't Me,0OaunKfsxkgBvPv68jBbmm,"Shaggy,Rik Rok",Pop,59,NaN,NaN,"Yo\n(Open up, man) What do you want, man?\n(My...",en
4,4,4,4,Ride Wit Me,1NTQbm1B08q3YW6AefylFo,T.I.,Pop,42,NaN,NaN,Where they at?\nIf you want to go and take a r...,en

In [ ]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1', 'name', 'id', 'artist',
       'genre', 'popularity', 'hit', 'lyricsBillboard', 'lyric', 'language'],
      dtype='object')

In [ ]:
df = df.drop(columns=['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1'])

In [ ]:
df.head()

,name,id,artist,genre,popularity,hit,lyricsBillboard,lyric,language
0,Yellow,36Owb6DDJbBFXi86x3X61z,Pity Party (Girls Club),Pop,62,NaN,NaN,"Love is sick, but we could try\nI really like,...",en
1,Kryptonite,6ZOBP3NvffbU4SZcrnt1k6,3 Doors Down,Pop,79,1.0,NaN,"Well, I took a walk around the world to ease m...",en
2,Ms. Jackson,0I3q5fE6wg7LIfHGngUTnV,Outkast,Pop,81,1.0,NaN,Yeah this one right here goes out to all the b...,en
3,It Wasn't Me,0OaunKfsxkgBvPv68jBbmm,"Shaggy,Rik Rok",Pop,59,NaN,NaN,"Yo\n(Open up, man) What do you want, man?\n(My...",en
4,Ride Wit Me,1NTQbm1B08q3YW6AefylFo,T.I.,Pop,42,NaN,NaN,Where they at?\nIf you want to go and take a r...,en

In [ ]:
#se añaden las columnas en las cuales se guardarán las features
#danceability, 'energy', 'key', 'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo', 'duration_ms', 'time_signature'
df2 = df.assign(danceability=0.0,energy=0.0, key=0.0, loudness=0.0, 
                mode=0.0, speechiness=0.0, acousticness=0.0, instrumentalness=0.0,
                liveness=0.0, valence=0.0, tempo=0.0, duration_ms=0.0, time_signature=0)

In [ ]:
df2.head()

,name,id,artist,genre,popularity,hit,lyricsBillboard,lyric,language,danceability,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
0,Yellow,36Owb6DDJbBFXi86x3X61z,Pity Party (Girls Club),Pop,62,NaN,NaN,"Love is sick, but we could try\nI really like,...",en,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,Kryptonite,6ZOBP3NvffbU4SZcrnt1k6,3 Doors Down,Pop,79,1.0,NaN,"Well, I took a walk around the world to ease m...",en,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,Ms. Jackson,0I3q5fE6wg7LIfHGngUTnV,Outkast,Pop,81,1.0,NaN,Yeah this one right here goes out to all the b...,en,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,It Wasn't Me,0OaunKfsxkgBvPv68jBbmm,"Shaggy,Rik Rok",Pop,59,NaN,NaN,"Yo\n(Open up, man) What do you want, man?\n(My...",en,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,Ride Wit Me,1NTQbm1B08q3YW6AefylFo,T.I.,Pop,42,NaN,NaN,Where they at?\nIf you want to go and take a r...,en,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [ ]:
error_ids = []

In [ ]:
for ind in df2.index:
  row = df2.iloc[ind]
  id = row["id"]
  try:
    features = sp.audio_features(id)[0]
    df2.at[ind,'danceability'] = features['danceability']
    df2.at[ind,'energy'] = features['energy']
    df2.at[ind,'key'] = features['key']
    df2.at[ind,'loudness'] = features['loudness']
    df2.at[ind,'mode'] = features['mode']
    df2.at[ind,'speechiness'] = features['speechiness']
    df2.at[ind,'acousticness'] = features['acousticness']
    df2.at[ind,'instrumentalness'] = features['instrumentalness']
    df2.at[ind,'liveness'] = features['liveness']
    df2.at[ind,'valence'] = features['valence']
    df2.at[ind,'tempo'] = features['tempo']
    df2.at[ind,'duration_ms'] = features['duration_ms']
    df2.at[ind,'time_signature'] = features['time_signature']
  except:
    print(ind)
    print(type(ind))
    error_ids.append(ind)
    pass

#danceability, 'energy', 'key', 'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo', 'duration_ms', 'time_signature'

31503
<class 'int'>

In [ ]:
df2.head()

,name,id,artist,genre,popularity,hit,lyricsBillboard,lyric,language,danceability,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
0,Yellow,36Owb6DDJbBFXi86x3X61z,Pity Party (Girls Club),Pop,62,NaN,NaN,"Love is sick, but we could try\nI really like,...",en,0.622,...,-9.142,1.0,0.0599,0.84800,0.477000,0.3960,0.655,125.068,134442.0,4
1,Kryptonite,6ZOBP3NvffbU4SZcrnt1k6,3 Doors Down,Pop,79,1.0,NaN,"Well, I took a walk around the world to ease m...",en,0.545,...,-5.708,0.0,0.0286,0.00664,0.000011,0.1680,0.543,99.009,233933.0,4
2,Ms. Jackson,0I3q5fE6wg7LIfHGngUTnV,Outkast,Pop,81,1.0,NaN,Yeah this one right here goes out to all the b...,en,0.843,...,-5.946,0.0,0.2690,0.14300,0.000000,0.0771,0.613,94.948,270507.0,4
3,It Wasn't Me,0OaunKfsxkgBvPv68jBbmm,"Shaggy,Rik Rok",Pop,59,NaN,NaN,"Yo\n(Open up, man) What do you want, man?\n(My...",en,0.852,...,-4.569,1.0,0.0642,0.05030,0.000000,0.3270,0.667,94.762,227547.0,4
4,Ride Wit Me,1NTQbm1B08q3YW6AefylFo,T.I.,Pop,42,NaN,NaN,Where they at?\nIf you want to go and take a r...,en,0.754,...,-4.582,0.0,0.2530,0.23300,0.000000,0.4370,0.778,156.932,244533.0,4

In [ ]:
df2.tail()

,name,id,artist,genre,popularity,hit,lyricsBillboard,lyric,language,danceability,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
39392,Enemigos,2YcaPMAFJiablDsRFAab4P,"Aitana,Reik",Pop,0,NaN,NaN,Ah-ah-ha-ah\nMe prometi esa noche no volverte ...,es,0.713,...,-3.609,0.0,0.1460,0.0502,0.000000,0.1720,0.702,89.997,197394.0,4
39393,DOSIS,0cDumxvNKhydP1Cmon2S6E,"Dvicio,Reik,ChocQuibTown",Pop,51,NaN,NaN,"Solo dios sabe, solo dios\nQue es lo que te pa...",es,0.747,...,-6.363,1.0,0.0481,0.1490,0.000001,0.1850,0.782,107.950,219189.0,4
39394,Resulta,1vKpHTveVVpoGs4ti0hsFW,"RIKI,Reik",Pop,37,NaN,NaN,"Bomboclat\nEasy Wonder\nYeh yeh yeh, yeh (Oh o...",es,0.835,...,-4.498,0.0,0.2490,0.1510,0.000006,0.1260,0.690,93.959,176000.0,4
39395,Ya Veremos,3FehHrtefcLcKNYtdJH4Ka,Reik,Pop,36,NaN,NaN,"Ya Veremos Lyrics\n\nMe buscas, te encuentro\n...",es,0.738,...,-8.199,0.0,0.1150,0.0314,0.002630,0.0920,0.576,93.900,165124.0,4
39396,Me Niego (Versión Pop) (feat. Ozuna & Wisin),1UF1mEUnXlSznLSML0BKEm,"Reik,Ozuna,Wisin",Pop,42,NaN,NaN,Me Niego (Versión Pop) Lyrics\n\nEs difícil ab...,es,0.604,...,-5.753,1.0,0.2070,0.3170,0.000000,0.0671,0.523,173.992,253987.0,4

In [ ]:
df2_clean = df2.drop(31503)

In [ ]:
df2_clean.iloc[35004]

name                              How Many More Times - 1993 Remaster
id                                             5VBzIn9cBH4BNa1c6Zilba
artist                                                   Led Zeppelin
genre                                                            Rock
popularity                                                         52
hit                                                               NaN
lyricsBillboard                                                   NaN
lyric               How many more times, treat me the way you wann...
language                                                           en
danceability                                                    0.322
energy                                                           0.68
key                                                               9.0
loudness                                                      -11.349
mode                                                              1.0
speechiness                                                     0.061
acousticness                                                    0.114
instrumentalness                                               0.0245
liveness                                                        0.434
valence                                                         0.518
tempo                                                         142.748
duration_ms                                                  508000.0
time_signature                                                      4
Name: 35005, dtype: object

In [ ]:
df2_clean.head()

,name,id,artist,genre,popularity,hit,lyricsBillboard,lyric,language,danceability,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
0,Yellow,36Owb6DDJbBFXi86x3X61z,Pity Party (Girls Club),Pop,62,NaN,NaN,"Love is sick, but we could try\nI really like,...",en,0.622,...,-9.142,1.0,0.0599,0.84800,0.477000,0.3960,0.655,125.068,134442.0,4
1,Kryptonite,6ZOBP3NvffbU4SZcrnt1k6,3 Doors Down,Pop,79,1.0,NaN,"Well, I took a walk around the world to ease m...",en,0.545,...,-5.708,0.0,0.0286,0.00664,0.000011,0.1680,0.543,99.009,233933.0,4
2,Ms. Jackson,0I3q5fE6wg7LIfHGngUTnV,Outkast,Pop,81,1.0,NaN,Yeah this one right here goes out to all the b...,en,0.843,...,-5.946,0.0,0.2690,0.14300,0.000000,0.0771,0.613,94.948,270507.0,4
3,It Wasn't Me,0OaunKfsxkgBvPv68jBbmm,"Shaggy,Rik Rok",Pop,59,NaN,NaN,"Yo\n(Open up, man) What do you want, man?\n(My...",en,0.852,...,-4.569,1.0,0.0642,0.05030,0.000000,0.3270,0.667,94.762,227547.0,4
4,Ride Wit Me,1NTQbm1B08q3YW6AefylFo,T.I.,Pop,42,NaN,NaN,Where they at?\nIf you want to go and take a r...,en,0.754,...,-4.582,0.0,0.2530,0.23300,0.000000,0.4370,0.778,156.932,244533.0,4

In [ ]:
df2_clean.tail()

,name,id,artist,genre,popularity,hit,lyricsBillboard,lyric,language,danceability,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
39392,Enemigos,2YcaPMAFJiablDsRFAab4P,"Aitana,Reik",Pop,0,NaN,NaN,Ah-ah-ha-ah\nMe prometi esa noche no volverte ...,es,0.713,...,-3.609,0.0,0.1460,0.0502,0.000000,0.1720,0.702,89.997,197394.0,4
39393,DOSIS,0cDumxvNKhydP1Cmon2S6E,"Dvicio,Reik,ChocQuibTown",Pop,51,NaN,NaN,"Solo dios sabe, solo dios\nQue es lo que te pa...",es,0.747,...,-6.363,1.0,0.0481,0.1490,0.000001,0.1850,0.782,107.950,219189.0,4
39394,Resulta,1vKpHTveVVpoGs4ti0hsFW,"RIKI,Reik",Pop,37,NaN,NaN,"Bomboclat\nEasy Wonder\nYeh yeh yeh, yeh (Oh o...",es,0.835,...,-4.498,0.0,0.2490,0.1510,0.000006,0.1260,0.690,93.959,176000.0,4
39395,Ya Veremos,3FehHrtefcLcKNYtdJH4Ka,Reik,Pop,36,NaN,NaN,"Ya Veremos Lyrics\n\nMe buscas, te encuentro\n...",es,0.738,...,-8.199,0.0,0.1150,0.0314,0.002630,0.0920,0.576,93.900,165124.0,4
39396,Me Niego (Versión Pop) (feat. Ozuna & Wisin),1UF1mEUnXlSznLSML0BKEm,"Reik,Ozuna,Wisin",Pop,42,NaN,NaN,Me Niego (Versión Pop) Lyrics\n\nEs difícil ab...,es,0.604,...,-5.753,1.0,0.2070,0.3170,0.000000,0.0671,0.523,173.992,253987.0,4

In [ ]:
df2_clean.to_csv("EsEnSongsDatasetWithFeatures.csv")
df2_clean.to_pickle("EsEnSongsDatasetWithFeatures")